In [1]:
import numpy as np

In [2]:
chat = np.array([
    [10, 15, 12, 8, 20, 18, 14],
    [5,  7,  3,  6,  4,  8,  2],
    [12, 10, 15, 20, 18, 14, 16]
])

In [3]:
print("Original Chat Data:", chat)

Original Chat Data: [[10 15 12  8 20 18 14]
 [ 5  7  3  6  4  8  2]
 [12 10 15 20 18 14 16]]


In [4]:
new_user = np.array([8, 12, 10, 15, 9, 11, 13])

In [5]:
chat = np.insert(chat, 3, new_user, axis=0)

In [6]:
print("After Adding New User:", chat)

After Adding New User: [[10 15 12  8 20 18 14]
 [ 5  7  3  6  4  8  2]
 [12 10 15 20 18 14 16]
 [ 8 12 10 15  9 11 13]]


In [7]:

total_messages = np.sum(chat, axis=1)
least_user = np.argmin(total_messages)

In [8]:
chat = np.delete(chat, least_user, axis=0)

In [9]:
print("After Removing User with Least Messages:", chat)

After Removing User with Least Messages: [[10 15 12  8 20 18 14]
 [12 10 15 20 18 14 16]
 [ 8 12 10 15  9 11 13]]
