In [1]:
import numpy as np


In [2]:
scores = np.array([
    [45, 60, 30, 75, 50],
    [20, 55, 80, 40, 65],
    [70, 35, 50, 90, 60]
])


In [3]:
result = scores[:, 1:4]

In [4]:
print(result)

[[60 30 75]
 [55 80 40]
 [35 50 90]]
