In [1]:
import numpy as np

In [2]:
ratings = np.array([
    4.5, 4.2, 3.9, 4.8, 4.1,
    3.8, 4.6, 4.3, 4.0, 4.7,
    3.5, 4.4, 4.9, 3.7, 4.2
])

In [3]:
new_ratings = ratings.reshape(3, 5)

In [4]:
print("3x5 array:")
print(new_ratings)

3x5 array:
[[4.5 4.2 3.9 4.8 4.1]
 [3.8 4.6 4.3 4.  4.7]
 [3.5 4.4 4.9 3.7 4.2]]


In [6]:
original = new_ratings.flatten()

In [7]:
print("1D array:")
print(original)

1D array:
[4.5 4.2 3.9 4.8 4.1 3.8 4.6 4.3 4.  4.7 3.5 4.4 4.9 3.7 4.2]
