In [1]:
import numpy as np

In [2]:
spotify = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32]
])

In [3]:
print("Original array:")
print(spotify)

Original array:
[[10 20 30]
 [15 25 35]
 [12 22 32]]


In [4]:
print("Using T:")
print(spotify.T)

Using T:
[[10 15 12]
 [20 25 22]
 [30 35 32]]


In [5]:
print("Using np.transpose():")
print(np.transpose(spotify))

Using np.transpose():
[[10 15 12]
 [20 25 22]
 [30 35 32]]
