In [1]:
import numpy as np

In [2]:
prices = np.array([120, 80, 150, 200, 90, 110,
                   75, 180, 250, 60, 130, 100])

In [3]:
print("Original:")
print(prices)

Original:
[120  80 150 200  90 110  75 180 250  60 130 100]


In [4]:
print("Ravel:")
print(prices.ravel())

Ravel:
[120  80 150 200  90 110  75 180 250  60 130 100]


In [5]:
print("Flatten:")
print(prices.flatten())

Flatten:
[120  80 150 200  90 110  75 180 250  60 130 100]


In [6]:
prices.resize(3, 4)


In [7]:
print("Resize:")
print(prices)

Resize:
[[120  80 150 200]
 [ 90 110  75 180]
 [250  60 130 100]]
