In [1]:
import numpy as np

In [2]:
steps = np.array([
    [3000, 5000],
    [4000, 6000],
    [3500, 5500],
    [4500, 7000],
    [5000, 8000]
])

In [3]:
print("Original 2D array:")
print(steps)

Original 2D array:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 7000]
 [5000 8000]]


In [4]:
one_d = steps.reshape(10)
print("1D array:")
print(one_d)

1D array:
[3000 5000 4000 6000 3500 5500 4500 7000 5000 8000]


In [5]:
two_d = one_d.reshape(5, 2)
print("Back to 2D:")
print(two_d)

Back to 2D:
[[3000 5000]
 [4000 6000]
 [3500 5500]
 [4500 7000]
 [5000 8000]]
